version: "3"

services:
  web:
    image: nginx:${NGINX_VERSION}
    volumes:
      - ${SOURCE_DIR}:/var/www/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    ports:
      - ${HTTP_HOST}:80
    environment:
      - NGINX_PORT:80
    links:
      - php
    networks:
      - front-tier
      - back-tier
    restart: always

  db:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
      - ${MYSQL_CONFG_FILE}:/etc/mysql/my.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    networks:
      - back-tier

  redis:
    image: redis:${REDIS_VERSION}
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "6379:6379"
    volumes:
      - ${REDIS_CONFIG_FILE}:/usr/local/etc/redis/redis.conf:ro
      - ${REDIS_DATA_DIR}:/data:rw
    networks:
      - back-tier
    restart: always

  php:
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ${SOURCE_DIR}:/var/www/:rw
      - ${PHP_CONFIG_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONFIG_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    links:
      - db
      - redis
    cap_add:
      - SYS_PTRACE
    restart: always
    networks:
      - back-tier


networks:
  front-tier:
  back-tier: